void reset_to_98(int *n);
int _putchar(char c);
void swap_int(int *a, int *b);
int _strien(char *s);
void _puts(char *str);
void print_rev(char *s);
void rev_string(char *s);
void puts(char *str);
void puts_half(char *str);
void print_array(int *a, int n);
char *_strcpy(char *dest, char *src);
int_atoi(char *s);
